### ISSUE TITLE
Delete error

### ISSUE THREAD

**Issue by ghost** [Halaszka/ToDo-List#5]
If you have for example 5 times the task "test" and you delete the second "test", all task's with the name "test" will be delete.
Fix, that you can have the same name of the task, but if i delete the second task, the  others will be excisting soon.

**Comment by Halaszka** [comment]
It's my turn to work. In the future, tasks will be stored in a local database.

**Comment by ghost** [comment]
Nice idea ;-)

Have fun ^^

**Comment by Halaszka** [comment]
Fixed! with the new Version 1.2 Blueberry 🍇
